'''
4.4 Optimal activity levels. Solve the optimal activity level problem described in exercise 4.17 in Convex Optimization, 
for the instance with problem data

A =
[[1, 2, 0, 1],
 [0, 0, 3, 1], 
 [0, 3, 1, 1], 
 [2, 1, 2, 5], 
 [1, 0, 3, 2]]

c_max = [100, 100, 100,  100, 100]

p = [3, 2, 7, 6]  

p_disc = [2, 1, 4, 2]

q = [4, 10, 5, 10]

You do not need to use the LP you are asked to find in exercise 4.17; 
you can just directly formulate the problem in CVXPY.

RESULTS TO DISPLAY:
------------------
Give the: 
 + optimal activity levels 
 + the revenue generated by each one 
 + the total revenue generated by the optimal solution. 
 + the average price per unit for each activity level, 
   i.e., the ratio of the revenue associated with an activity, to the activity level. 
   (These numbers should be between the basic and discounted prices for each activity.) 

Give a very brief story explaining, or at least commenting on, the solution you find.

=====================================================================================

4.17 Optimal activity levels. 

We consider the selection of n nonnegative activity levels, denoted x₁, …, xₙ. 
These activities consume m resources, which are limited.

Activity j consumes Aᵢⱼ @ xⱼ of resource i, where Aᵢⱼ are given. 

The total resource consumption is additive, so the total of resource i consumed is cᵢ = ∑ⱼ₌₁ⁿ Aᵢⱼ xⱼ. 
(Ordinarily we have Aᵢⱼ ≥ 0, i.e., activity j consumes resource i. 
But we allow the possibility that Aᵢⱼ < 0, which means that activity j actually generates resource i as a by-product.) 

Each resource consumption is limited: we must have cᵢ ≤ cᵢ^max, where cᵢ^max are given. 

Each activity generates revenue, which is a piecewise-linear concave function of the activity level:
           { pⱼ xⱼ                           0 ≤ xⱼ ≤ qⱼ
rⱼ(xⱼ) =  {
           { pⱼ qⱼ + p_discⱼ (xⱼ - qⱼ)        xⱼ ≥ qⱼ.

Here pⱼ > 0 is the basic price, 
     qⱼ > 0 is the quantity discount level, 
 and p_discⱼ is the quantity discount price, 
for (the product of) activity j. (We have 0 < p_discⱼ < pⱼ.) 

The total revenue is the sum of the revenues associated with each activity, i.e., ∑ⱼ₌₁ⁿ rⱼ(xⱼ). 
The goal is to choose activity levels that maximize the total revenue while respecting the resource limits. 
Show how to formulate this problem as an LP.
'''

import cvxpy as cp
import numpy as np

#-----------
## Define the constants
#-----------

# Define activity resource consumption matrix A
A_rc = cp.Constant(
     name = "A_rc",
     value = np.array(
         [[1, 2, 0, 1],
          [0, 0, 3, 1], 
          [0, 3, 1, 1], 
          [2, 1, 2, 5], 
          [1, 0, 3, 2]]
     )
)

# Define the consumtion limits vector c[i]
c_max = cp.Constant(
    name = "c", 
    value = [100, 100, 100,  100, 100]
)

# Define the price vector p[i]
p = cp.Constant(
    name = "p",
    value = [3, 2, 7, 6]
)

# Define the price discount rate vector p_disc[i]
p_disc = cp.Constant(
    name = "p_disc",
    value = [2, 1, 4, 2]
)

# Define the quantity of discount vector q[i]
q = cp.Constant(
    name = "q",
    value = [4, 10, 5, 10]
)

#-----------
## Define the variables
#-----------

# Define activity levels vector x[i] 
x = cp.Variable(name = "x", shape = (4))

# Define the activity levels vector below the discount quantity x_below[i]
x_below = cp.Variable(name = "x_below", shape = (4))

# Define the activity levels vector above the discount quantity x_above[i]
x_above = cp.Variable(name = "x_above", shape = (4))

''' x = x_below + x_above '''

#-----------
## Define the objective function
#-----------
revenue_obj_func = cp.Maximize(x_below@p + p_disc@x_above)

#-----------
## Define the constraints
#-----------
# Define constraints of x_below and x_above (hence define the x implicitly)
opt_constraints = [
    x_below + x_above == x,
    -x_below <= 0, # x_below >= 0
    x_below <= q,
    -x_above <= 0, # x_above >= 0 
]

# Add the resource consumtion limit
opt_constraints.extend(
    A_rc[i, :] @ x <= c_max[i]
    for i, _ in enumerate(c_max)
)

#-----------
## Define the problem and solve
#-----------

problem = cp.Problem(
    objective = revenue_obj_func,
    constraints = opt_constraints
)

problem.solve()

print(
    (
        f"Status: {problem.status}\n"
        f"Optimal Activity Levels: {x.value}\n"
        f"Optimal Revenue generated by each Activity: {x_below.value*p.value + p_disc.value*x_above.value}\n" # use * to avoid dot product
        f"Total Optimal Revenue: {problem.value}\n"
        f"Average Price Per Unit of Each Activity: {(problem.value/x.shape[0] / x.value)}"
    )
)

# Status: optimal
# Optimal Activity Levels: [ 4.         22.49999999 31.          1.5       ]
# Optimal Revenue generated by each Activity: [ 12.          32.49999999 139.           9.00000001]
# Total Optimal Revenue: 192.49999999953468
# Average Price Per Unit of Each Activity: [12.03125     2.13888889  1.55241935 32.08333329]